### ISSUE TITLE
Interrobang::FalsePredicate should inherit from StandardError

### ISSUE THREAD

**Issue by PikachuEXE** [fny/interrobang#1]
Since the default `rescue` rescues StandardError not Exception

**Comment by fny** [comment]
Thanks! New release should be cut tomorrow once I figure out what's going on with Travis.

**Comment by PikachuEXE** [comment]
@fny It seems the successful builds are NOT run on container based intrastructure, which they haven't updated the `bundler` version for jruby yet.
So try setting `sudo: true` in `travis.yml` to force NOT to use that.
Side effect would be slower build.

**Comment by fny** [comment]
Looks like specifying JRuby 9K did the trick. Just cut a new release.
